version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/css-inline"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/c"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/python"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/ruby"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bindings/javascript"
    schedule:
      interval: "daily"
