# frozen_string_literal: true

require "rake/extensiontask"
require 'rspec/core/rake_task'
require "rb_sys"
require "rb_sys/toolchain_info"

task default: :spec

spec = Bundler.load_gemspec("css_inline.gemspec")
spec.requirements.clear
spec.required_ruby_version = nil
spec.required_rubygems_version = nil
spec.extensions.clear
spec.files -= Dir["ext/**/*"]

Rake::ExtensionTask.new("css_inline", spec) do |c|
  c.lib_dir = "lib/css_inline"
  c.cross_compile = true
  c.cross_platform = RbSys::ToolchainInfo.supported_ruby_platforms
end

task :dev do
  ENV["RB_SYS_CARGO_PROFILE"] = "dev"
end

RSpec::Core::RakeTask.new(:test) do |task|
  task.rspec_opts = [ "-f documentation" ]
end

task test: :compile

task bench: :compile do
  ruby "test/bench.rb"
end
