// Generated by dts-bundle-generator v9.1.0

/* tslint:disable */
/* eslint-disable */
export interface InlineOptions {
	inlineStyleTags?: boolean;
	keepStyleTags?: boolean;
	keepLinkTags?: boolean;
	baseUrl?: string;
	loadRemoteStylesheets?: boolean;
	extraCss?: string;
	preallocateNodeCapacity?: number;
}
export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;
/**
 * Initialize Wasm module
 * @param module_or_path WebAssembly Module or .wasm url
 *
 */
export declare const initWasm: (module_or_path: Promise<InitInput> | InitInput) => Promise<void>;
export declare function inline(html: string, options?: InlineOptions): string;
export declare function inlineFragment(html: string, css: string, options?: InlineOptions): string;
export declare function version(): string;

export {};
