name: Update Github Pages

on:
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Update website
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mv bindings/javascript/wasm/ docs/
          touch docs/.nojekyll
          echo "css-inline.org" > docs/CNAME
          git add --force docs/
          git commit -m "chore: build pages"
          git push --force origin HEAD:gh-pages
