name: WASM Release

on:
  push:
    tags:
      - wasm-v*

jobs:
  wasm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install wasm-pack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack
      - name: Build package
        run: wasm-pack build --release --target nodejs
        working-directory: ./bindings/wasm
      - name: Fix package name
        # wasm-pack generates the package name from the crate name.
        # Since the original Rust crate has this name (`css-inline`), the WASM crate has `css-inline-wasm` to
        # avoid conflicts during the build. The easiest way to handle it is to rename it inside the package.json file.
        run: sed -i 's/css-inline-wasm/css-inline/' pkg/package.json
        working-directory: ./bindings/wasm
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: npm publish --access public
        working-directory: ./bindings/wasm/pkg
